# Generated by Django 3.2.16 on 2022-12-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, unique=True)),
                ('Address', models.CharField(max_length=255)),
                ('Name_of_Organization', models.CharField(max_length=255, unique=True)),
                ('Number_of_Employees', models.IntegerField()),
                ('First_Director', models.CharField(max_length=255)),
                ('Second_Director', models.CharField(max_length=255)),
                ('Third_Director', models.CharField(max_length=255)),
                ('Phone_Number', models.IntegerField(max_length=255)),
                ('Country', models.CharField(choices=[('Alg', 'Algeria'), ('Ang', 'Angola'), ('Ben', 'Benin'), ('Bot', 'Botswana')], max_length=3)),
                ('Organization_Registration_No', models.IntegerField()),
                ('CAC_No', models.CharField(default='RnNulled', max_length=255)),
                ('Proposal_Status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=255)),
                ('Correspondence_Status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=255)),
                ('Receiver_Status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=255)),
                ('Clearance_Status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=255)),
            ],
        ),
    ]
