# Generated by Django 3.2.16 on 2022-12-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collect',
            new_name='CompanyProfile',
        ),
    ]
