# Generated by Django 3.2.16 on 2022-12-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='CAC_No',
            field=models.CharField(max_length=255),
        ),
    ]
